### ISSUE TITLE
How can I edit these characteristics?

### ISSUE THREAD

**Issue by zombodotcom** [jasoncoon/esp32-fastled-ble#1]
![image](https://user-images.githubusercontent.com/13477955/37867735-19493f74-2f62-11e8-82ec-0d5edc7656dd.png)

I have my app setup like this right now

![image](https://user-images.githubusercontent.com/13477955/37867729-1311ab96-2f62-11e8-942b-bab33c463243.png)

I tried to add the 75c34563-a7ba-4ff3-8d9f-832fa1cd5a0e which is coming out to the pattern in the UUID on serial, but adding that 
![image](https://user-images.githubusercontent.com/13477955/37867750-37a408d2-2f62-11e8-8994-516a23d39aa0.png)
Doesn't want it to work at all. 

I am just trying to figure out what I need to send to the esp32 through my app to make it change patterns with that UUID it has given to the pattern field. 

Off and On Work fine but that's the only thing written in the FieldCallbacks. For my BLE project I had to set each thing to search what pattern it was through rxValue.find "pattern name" !=-1

**Comment by jasoncoon** [comment]
Sorry, not sure yet.  This sketch is still very much an experimental work in progress.  I hope to revisit it soon.

**Comment by zombodotcom** [comment]
Alright, and it looked like you were using a specific UUID for the Feather right?

For the esp32 Wroom its 
`#define SERVICE_UUID           "6E400001-B5A3-F393-E0A9-E50E24DCCA9E"`

all other UUID's don't seem to want it to interact. I can change the patterns with the app right now just adding stuff like 

```
   // Do stuff based on the command received from the app
        if (rxValue.find("push") != -1) {
          Serial.println("Turning ON!");
             Serial.print(String(currentPatternIndex));
             currentPatternIndex++;
        }
```

I'll keep working on it. as soon as I find out how to change the value of those characteristics it should be a piece of cake to make an app for it like my other lumos board. 

thanks again!

**Comment by zombodotcom** [comment]
You might like to look into this, It includes Thunkable for the app as well and a working version of OTA for the esp32. 
![image](https://user-images.githubusercontent.com/13477955/37878083-cf734416-3020-11e8-8209-446f63722d7d.png)
```
//		pCharacteristic->setAccessPermissions(ESP_GATT_PERM_READ_ENCRYPTED | ESP_GATT_PERM_WRITE_ENCRYPTED);
		pCharacteristic->setCallbacks(new CharacteristicCallback1());

		BLECharacteristic* pCharacteristic1 = pService->createCharacteristic(			// IP
			BLEUUID("00005b62-2745-479b-b006-56f3b4043c2c"),
			BLECharacteristic::PROPERTY_READ  |
			BLECharacteristic::PROPERTY_WRITE
		);

//		pCharacteristic1->setAccessPermissions(ESP_GATT_PERM_READ_ENCRYPTED | ESP_GATT_PERM_WRITE_ENCRYPTED);
		pCharacteristic1->setCallbacks(new CharacteristicCallback2());

		BLECharacteristic* pCharacteristic2 = pService->createCharacteristic(			// port
			BLEUUID("00005b63-2745-479b-b006-56f3b4043c2c"),
			BLECharacteristic::PROPERTY_READ  |
			BLECharacteristic::PROPERTY_WRITE
		);

//		pCharacteristic2->setAccessPermissions(ESP_GATT_PERM_READ_ENCRYPTED | ESP_GATT_PERM_WRITE_ENCRYPTED);
		pCharacteristic2->setCallbacks(new CharacteristicCallback3());

		BLECharacteristic* pCharacteristic3 = pService->createCharacteristic(			// path
			BLEUUID("00005b64-2745-479b-b006-56f3b4043c2c"),
			BLECharacteristic::PROPERTY_READ  |
			BLECharacteristic::PROPERTY_WRITE
		);

//		pCharacteristic3->setAccessPermissions(ESP_GATT_PERM_READ_ENCRYPTED | ESP_GATT_PERM_WRITE_ENCRYPTED);
		pCharacteristic3->setCallbacks(new CharacteristicCallback4());
```
