### ISSUE TITLE
Alternative?

### ISSUE THREAD

**Issue by jordanadania** [jasoncoon/esp32-fastled-ble#2]
Since I can't find a way to change patterns with bluetooth using the esp32 I was wondering what my alternatives are for using your webserver remotely.

I think someone mentioned using a raspberry pi to create a wifi network for the esp32/8266 to talk to. Would this work? What is this process called so I may google it?

Oh and, is there a place to donate to this project? And how much donation required to get it moving again?

**Comment by zombodotcom** [comment]
My new version of this without ble that I based on coons work features ap mode and station mode at the same time.

https://github.com/zombodotcom/esp32-Async-FastLED-Audio/blob/master/esp32-fastled-webserver-ASYNC-Audio/wifi.h
That's the code showing station mode and ap mode working.

But honestly if you just want to use another esp32 as an access point for the esp32 you could do that too.

https://techtutorialsx.com/2017/07/26/esp32-arduino-setting-a-soft-ap/

It's called a soft ap. ( Software access point ) 

I'm also not the creator of this project but I meddled with Jason's code a lot when learning about fastled and stuff. His work is a godsend

**Comment by jordanadania** [comment]
Sorry, what is station mode?

**Comment by zombodotcom** [comment]
Sta ,station mode , is basic connections as in I want to connect to an already established wifi. Ap mode is basically making it be its own router

**Comment by jordanadania** [comment]
oh my goodness...

Thank you so much. AP mode sounds like what I want. Routerless webserver would be perfect. AND AUDIO TOOO??!?! Is this christmas?!? <3

**Comment by jordanadania** [comment]
and yes. Mr. Coon is my LED god/idol.

we all need someone to look up to.

**Comment by jordanadania** [comment]
I left my esp32 in my car and I think the Florida heat fried it?

Does AP Mode work on an 8266?
